//login
export const NEW_USER = 'New User?'
export const EXISTING_USER = 'Already have an account?'
export const UNAUTHORIZED = 'Please sign up to continue'
export const SERVER_ERROR = 'Server Error. Please try again'
export const USERNAME_EMPTY_ERROR = 'Please enter a username'
export const USERNAME_SHORT_ERROR = 'Username must be 3 characters minimum'
export const PASSWORD_EMPTY_ERROR = 'Please enter a password'
export const PASSWORD_SHORT_ERROR = 'Password must be 8 characters minimum'
export const PASSWORD_NUMBER_ERROR = 'Password must contain a number'
export const SIGNING_IN = 'Signing in'
export const SIGN_IN = 'Sign In'
export const FULLNAME_EMPTY_ERROR = 'Please enter your full name'
export const FULLNAME_SHORT_ERROR = 'This field must be 5 characters minimum'
export const CREATE_MY_ACCOUNT = 'Create my account'
export const CREATING_ACCOUNT = 'Creating account'
export const CREATE_ACCOUNT = 'Create Account'
